framework:
    secret: '%env(APP_SECRET)%' # Utilise la clé secrète définie dans .env
    router:
        utf8: true
    csrf_protection: true # Active la protection CSRF (utile pour les formulaires)
    http_method_override: true
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto # Rend les cookies sécurisés automatiquement en production
    php_errors:
        log: true # Journalise les erreurs PHP dans les logs Symfony
